canciones = [
    ("Maldita costumbre", "Morat", "Balas Perdidas"),
    ("Como te atreves", "Morat", "Sobre el amor y sus efectos secundarios"),
    ("No se va", "Morat", "Si ayer fuera hoy"),
    ("Paris", "Morat", "Si ayer fuera hoy"),
    ("A donde vamos", "Morat", "A donde vamos"),
    ("Besos en guerra", "Morat", "Sobre el amor y sus efectos secundarios"),
    ("Date la vuelta", "Luis Fonsi", "Vida"),
    ("Perfect", "Ed Sheeran", "Divide"),
    ("Shape of You", "Ed Sheeran", "Divide"),
    ("Photograph", "Ed Sheeran", "x"),
    ("Thinking Out Loud", "Ed Sheeran", "x"),
    ("Shivers", "Ed Sheeran", "="),
    ("Bad Habits", "Ed Sheeran", "="),
    ("Castle on the Hill", "Ed Sheeran", "Divide"),
    ("Galway Girl", "Ed Sheeran", "Divide"),
    ("Blinding Lights", "The Weeknd", "After Hours"),
    ("Save Your Tears", "The Weeknd", "After Hours"),
    ("Starboy", "The Weeknd", "Starboy"),
    ("Die For You", "The Weeknd", "Starboy"),
    ("The Hills", "The Weeknd", "Beauty Behind the Madness"),
    ("Cant Feel My Face", "The Weeknd", "Beauty Behind the Madness"),
    ("Call Out My Name", "The Weeknd", "My Dear Melancholy"),
    ("As It Was", "Harry Styles", "Harrys House"),
    ("Watermelon Sugar", "Harry Styles", "Fine Line"),
    ("Adore You", "Harry Styles", "Fine Line"),
    ("Sign of the Times", "Harry Styles", "Harry Styles"),
    ("Late Night Talking", "Harry Styles", "Harrys House"),
    ("Golden", "Harry Styles", "Fine Line"),
    ("Falling", "Harry Styles", "Fine Line"),
    ("Satellite", "Harry Styles", "Harrys House"),
    ("Viva la Vida", "Coldplay", "Viva la Vida or Death and All His Friends"),
    ("Yellow", "Coldplay", "Parachutes"),
    ("The Scientist", "Coldplay", "A Rush of Blood to the Head"),
    ("Fix You", "Coldplay", "X&Y"),
    ("Paradise", "Coldplay", "Mylo Xyloto"),
    ("A Sky Full of Stars", "Coldplay", "Ghost Stories"),
    ("Clocks", "Coldplay", "A Rush of Blood to the Head"),
    ("Adventure of a Lifetime", "Coldplay", "A Head Full of Dreams"),
    ("Hymn for the Weekend", "Coldplay", "A Head Full of Dreams"),
    ("Sparks", "Coldplay", "Parachutes"),
    ("Levitating", "Dua Lipa", "Future Nostalgia"),
    ("Dont Start Now", "Dua Lipa", "Future Nostalgia"),
    ("New Rules", "Dua Lipa", "Dua Lipa"),
    ("Houdini", "Dua Lipa", "Radical Optimism"),
    ("Dance The Night", "Dua Lipa", "Barbie The Album"),
    ("Flowers", "Miley Cyrus", "Endless Summer Vacation"),
    ("Used To Be Young", "Miley Cyrus", "Endless Summer Vacation"),
    ("Wrecking Ball", "Miley Cyrus", "Bangerz"),
    ("Party In The U.S.A.", "Miley Cyrus", "The Time of Our Lives"),
    ("Someone Like You", "Adele", "21"),
    ("Rolling in the Deep", "Adele", "21"),
    ("Easy On Me", "Adele", "30"),
    ("Set Fire to the Rain", "Adele", "21"),
    ("Hello", "Adele", "25"),
    ("Anti-Hero", "Taylor Swift", "Midnights"),
    ("Cruel Summer", "Taylor Swift", "Lover"),
    ("Lover", "Taylor Swift", "Lover"),
    ("Blank Space", "Taylor Swift", "1989"),
    ("Style", "Taylor Swift", "1989"),
    ("Shake It Off", "Taylor Swift", "1989"),
    ("Cardigan", "Taylor Swift", "Folklore"),
    ("Willow", "Taylor Swift", "Evermore"),
    ("Fortnight", "Taylor Swift", "The Tortured Poets Department"),
    ("Espresso", "Sabrina Carpenter", "Short n Sweet"),
    ("Please Please Please", "Sabrina Carpenter", "Short n Sweet"),
    ("Feather", "Sabrina Carpenter", "Emails I Cant Send"),
    ("Nonsense", "Sabrina Carpenter", "Emails I Cant Send"),
    ("Good 4 U", "Olivia Rodrigo", "Sour"),
    ("Drivers License", "Olivia Rodrigo", "Sour"),
    ("Vampire", "Olivia Rodrigo", "Guts"),
    ("Deja Vu", "Olivia Rodrigo", "Sour"),
    ("Bad Idea Right?", "Olivia Rodrigo", "Guts"),
    ("Stay", "The Kid LAROI", "F*CK LOVE 3: OVER YOU"),
    ("Without You", "The Kid LAROI", "F*CK LOVE 3: OVER YOU"),
    ("Believer", "Imagine Dragons", "Evolve"),
    ("Thunder", "Imagine Dragons", "Evolve"),
    ("Demons", "Imagine Dragons", "Night Visions"),
    ("Radioactive", "Imagine Dragons", "Night Visions"),
    ("Enemy", "Imagine Dragons", "Mercury Act 1"),
    ("Sunflower", "Post Malone", "Hollywoods Bleeding"),
    ("Circles", "Post Malone", "Hollywoods Bleeding"),
    ("Rockstar", "Post Malone", "Beerbongs & Bentleys"),
    ("Congratulations", "Post Malone", "Stoney"),
    ("I Had Some Help", "Post Malone", "F-1 Trillion"),
    ("Unholy", "Sam Smith", "Gloria"),
    ("Stay With Me", "Sam Smith", "In the Lonely Hour"),
    ("Too Good at Goodbyes", "Sam Smith", "The Thrill of It All"),
    ("Senorita", "Shawn Mendes", "Shawn Mendes"),
    ("Treat You Better", "Shawn Mendes", "Illuminate"),
    ("Theres Nothing Holdin Me Back", "Shawn Mendes", "Illuminate"),
    ("Havana", "Camila Cabello", "Camila"),
    ("Bam Bam", "Camila Cabello", "Familia"),
    ("Never Be the Same", "Camila Cabello", "Camila"),
    ("Peaches", "Justin Bieber", "Justice"),
    ("Sorry", "Justin Bieber", "Purpose"),
    ("Love Yourself", "Justin Bieber", "Purpose"),
    ("What Do You Mean?", "Justin Bieber", "Purpose"),
    ("Intentions", "Justin Bieber", "Changes"),
    ("Calm Down", "Rema", "Rave & Roses"),
    ("Kiss Me More", "Doja Cat", "Planet Her"),
]